from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass(frozen=True, slots=True)
class RouteFamilySpec:
    route_family: str
    subsystem: str
    owned_operations: tuple[str, ...]
    owned_target_types: tuple[str, ...]
    required_context_types: tuple[str, ...] = ()
    allowed_context_types: tuple[str, ...] = ()
    disallowed_context_types: tuple[str, ...] = ()
    risk_classes: tuple[str, ...] = ()
    positive_intent_signals: tuple[str, ...] = ()
    negative_intent_signals: tuple[str, ...] = ()
    near_miss_examples: tuple[str, ...] = ()
    missing_context_behavior: str = ""
    ambiguity_behavior: str = "route native and clarify when ownership is clear but bindings conflict"
    generic_provider_allowed_when: str = "no operation, target, or context ownership"
    clarification_template: str = "Which context should I use?"
    expected_result_states: tuple[str, ...] = ("completed", "dry_run", "needs_clarification", "blocked_missing_context")
    tool_candidates: tuple[str, ...] = ()
    confidence_floor: float = 0.58
    overcapture_guards: tuple[str, ...] = ()
    telemetry_fields: tuple[str, ...] = (
        "intent_frame",
        "route_family_spec",
        "candidate_score",
        "score_factors",
        "decline_reasons",
        "missing_preconditions",
    )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def default_route_family_specs() -> dict[str, RouteFamilySpec]:
    specs = [
        _spec(
            "calculations",
            "calculations",
            operations=("calculate", "verify", "explain", "compare"),
            targets=("prior_calculation", "prior_result", "unknown"),
            required=("calculation_context",),
            allowed=("prior_calculation", "prior_result", "selected_text"),
            disallowed=("calculator app", "website", "file"),
            risks=("read_only",),
            positive=("arithmetic expression", "numeric expression", "answer", "compute", "solve", "previous answer"),
            negative=("calculator app", "math teaching ideas", "neural network comparison"),
            near=("open calculator app", "compare conceptual models", "why multiplication works"),
            missing="route calculations and clarify for calculation_context",
            tools=(),
        ),
        _spec(
            "browser_destination",
            "browser",
            operations=("open", "search", "inspect"),
            targets=("url", "website", "current_page"),
            required=("destination_context",),
            allowed=("url", "website", "current_page"),
            disallowed=("app", "file", "software_package"),
            risks=("external_browser_open", "internal_surface_open"),
            positive=("url", "website", "page", "site", "link"),
            negative=("open app", "software install", "file path"),
            near=("open link-building ideas", "what is a website", "open Chrome"),
            missing="route browser_destination and clarify for destination_context",
            tools=("external_open_url", "deck_open_url"),
        ),
        _spec(
            "app_control",
            "system",
            operations=("open", "launch", "close", "quit"),
            targets=("app", "current_app"),
            required=("app_context",),
            allowed=("app", "current_app"),
            disallowed=("install", "update", "uninstall", "software_package", "website", "file"),
            risks=("external_app_open",),
            positive=("launch app", "open app", "quit app", "close app", "focus window"),
            negative=("install software", "uninstall software", "open website", "open file path"),
            near=("quit procrastinating", "open source idea", "close reading notes"),
            missing="route app_control and clarify for app target",
            tools=("app_control", "window_control"),
        ),
        _spec(
            "file",
            "files",
            operations=("open", "inspect"),
            targets=("file", "folder", "current_file"),
            required=("file_context",),
            allowed=("file", "folder", "current_file"),
            disallowed=("app", "website"),
            risks=("internal_surface_open", "read_only"),
            positive=("file", "document", "doc", "path", "read", "open"),
            negative=("app launch", "website page", "conceptual file naming"),
            near=("what is a file", "file naming philosophy"),
            missing="route file and clarify for file_context",
            tools=("deck_open_file", "external_open_file", "file_reader"),
        ),
        _spec(
            "file_operation",
            "files",
            operations=("save", "update", "repair"),
            targets=("file", "folder", "current_file"),
            required=("file_context",),
            allowed=("file", "folder", "current_file"),
            disallowed=("app", "website"),
            risks=("local_mutation", "destructive", "dry_run_plan"),
            positive=("rename file", "move file", "delete file", "tag file", "archive file"),
            negative=("rename an idea", "move on"),
            near=("rename this concept", "archive old memories"),
            missing="route file_operation and clarify for file_context",
            tools=("file_operation",),
        ),
        _spec(
            "context_action",
            "context",
            operations=("explain", "save", "assemble", "inspect", "open"),
            targets=("selected_text", "highlighted"),
            required=("context",),
            allowed=("selected_text", "highlighted"),
            disallowed=("website", "app"),
            risks=("read_only", "dry_run_plan"),
            positive=("selected text", "highlighted text", "clipboard"),
            negative=("selection bias concept", "highlighted typography ideas"),
            near=("selected-text markup concept", "explain selection bias"),
            missing="route context_action and clarify for context",
            tools=("context_action",),
        ),
        _spec(
            "comparison",
            "files",
            operations=("compare",),
            targets=("file", "selected_text", "prior_result"),
            required=("comparison_targets",),
            allowed=("file", "selected_text", "prior_result"),
            disallowed=("conceptual comparison", "neural network", "startup pricing"),
            risks=("read_only",),
            positive=("compare files", "compare selected", "diff documents"),
            negative=("neural network", "architecture", "startup pricing", "conceptual"),
            near=("compare technology choices conceptually", "compare model architecture ideas"),
            missing="route comparison and clarify for concrete comparison targets",
            tools=(),
        ),
        _spec(
            "screen_awareness",
            "screen_awareness",
            operations=("inspect", "open", "verify"),
            targets=("visible_ui", "visible_target"),
            required=("visible_screen",),
            allowed=("visible_ui", "visible_target"),
            disallowed=("conceptual screen topic",),
            risks=("read_only", "dry_run_plan"),
            positive=("button", "menu", "icon", "field", "panel", "visible target"),
            negative=("screenwriting", "coverage summary", "conceptual screen question"),
            near=("press coverage summary", "click that"),
            missing="route screen_awareness and clarify for visible_screen",
            tools=(),
        ),
        _spec(
            "workspace_operations",
            "workspace",
            operations=("assemble", "save", "open", "search"),
            targets=("workspace",),
            required=(),
            allowed=("workspace", "file", "folder"),
            disallowed=("conceptual workspace article",),
            risks=("read_only", "dry_run_plan", "local_mutation"),
            positive=("workspace", "project setup", "docs workspace"),
            negative=("workspace design theory",),
            near=("what is a workspace", "workspace philosophy"),
            missing="clarify when target workspace is ambiguous",
            tools=("workspace_restore", "workspace_assemble", "workspace_save", "workspace_list"),
        ),
        _spec(
            "routine",
            "routine",
            operations=("save", "open", "launch"),
            targets=("routine", "prior_result"),
            required=("routine_context", "steps_or_recent_action"),
            allowed=("routine", "prior_result", "workspace"),
            disallowed=("conceptual routine discussion",),
            risks=("dry_run_plan", "local_mutation"),
            positive=("routine", "saved workflow", "run cleanup"),
            negative=("routine concept advice",),
            near=("what is a routine", "habit routine design"),
            missing="route routine and clarify for routine_context or steps_or_recent_action",
            tools=("routine_execute", "routine_save"),
        ),
        _spec(
            "workflow",
            "workflow",
            operations=("assemble", "open", "launch"),
            targets=("workspace", "routine", "unknown"),
            required=(),
            allowed=("workspace", "file", "folder"),
            disallowed=("conceptual workflow discussion",),
            risks=("dry_run_plan",),
            positive=("workflow", "set up writing environment"),
            negative=("workflow theory",),
            near=("explain a workflow",),
            missing="clarify when the workflow target is absent",
            tools=("workflow_execute",),
        ),
        _spec(
            "task_continuity",
            "workspace",
            operations=("status", "inspect", "assemble"),
            targets=("workspace", "prior_result", "selected_text"),
            required=("workspace_context",),
            allowed=("workspace", "prior_result", "selected_text"),
            disallowed=("conceptual tasks",),
            risks=("read_only",),
            positive=("where left off", "next steps", "resume", "turn selected text into tasks"),
            negative=("task management philosophy",),
            near=("subject-area next-step question",),
            missing="route and clarify if no task/workspace continuity exists",
            tools=("workspace_where_left_off", "workspace_next_steps", "context_action"),
        ),
        _spec(
            "discord_relay",
            "discord_relay",
            operations=("send",),
            targets=("discord_recipient", "selected_text"),
            required=("payload", "destination"),
            allowed=("selected_text", "prior_result", "discord_recipient"),
            disallowed=("general Discord discussion",),
            risks=("external_send",),
            positive=("send to Discord", "share to Discord", "relay"),
            negative=("Discord architecture",),
            near=("general Discord concept", "Discord documentation format"),
            missing="route discord_relay and clarify for payload and destination",
            tools=(),
        ),
        _spec(
            "software_control",
            "software_control",
            operations=("install", "uninstall", "update", "repair"),
            targets=("software_package",),
            required=("software_target",),
            allowed=("software_package",),
            disallowed=("app quit", "app open", "website", "file"),
            risks=("software_lifecycle",),
            positive=("install software", "update software", "uninstall software", "repair software"),
            negative=("quit app", "open app", "remove text"),
            near=("remove anxiety", "update me on news"),
            missing="route software_control and clarify for software target",
            tools=(),
        ),
        _spec(
            "software_recovery",
            "software_recovery",
            operations=("repair", "status", "verify"),
            targets=("system_resource",),
            required=(),
            allowed=("system_resource",),
            disallowed=("software install", "software uninstall", "app quit"),
            risks=("dry_run_plan", "software_lifecycle"),
            positive=("fix wifi", "repair network", "connectivity checks", "flush dns", "restart explorer"),
            negative=("fix writing", "network architecture", "neural network"),
            near=("fix my essay", "compare neural networks"),
            missing="route software_recovery and clarify for recovery target",
            tools=("repair_action",),
        ),
        _spec(
            "unsupported",
            "safety",
            operations=("unknown", "open", "send"),
            targets=("unknown",),
            required=(),
            allowed=("unknown",),
            disallowed=(),
            risks=("read_only", "external_send", "destructive"),
            positive=("book", "buy", "purchase", "order", "pay now"),
            negative=(),
            near=(),
            missing="block unsupported real-world external commitments",
            tools=(),
        ),
        _spec(
            "watch_runtime",
            "operations",
            operations=("status", "inspect"),
            targets=("system_resource", "app", "current_app"),
            required=(),
            allowed=("system_resource", "app", "current_app"),
            disallowed=("conceptual network", "conceptual app"),
            risks=("read_only",),
            positive=("apps running", "what did I miss", "window status"),
            negative=("app architecture ideas", "neural network"),
            near=("which app architecture is better",),
            missing="status routes do not usually need clarification",
            tools=("active_apps", "activity_summary", "window_status"),
        ),
        _spec(
            "window_control",
            "system",
            operations=("status", "inspect"),
            targets=("current_app", "app"),
            required=(),
            allowed=("current_app", "app"),
            disallowed=("conceptual window",),
            risks=("read_only",),
            positive=("windows open", "active windows", "focused window"),
            negative=("window pattern", "window architecture"),
            near=("which application window pattern should I use",),
            missing="window status does not usually need clarification",
            tools=("window_status",),
        ),
        _spec(
            "network",
            "system",
            operations=("status", "inspect"),
            targets=("system_resource",),
            required=(),
            allowed=("system_resource",),
            disallowed=("neural network", "network architecture"),
            risks=("read_only",),
            positive=("wifi", "wi-fi", "network", "connection", "ssid", "internet status"),
            negative=("neural network", "network architecture", "network graph concept"),
            near=("conceptual model comparison", "compare network architectures"),
            missing="network status does not require deictic context",
            tools=("network_status",),
        ),
        _spec(
            "maintenance",
            "maintenance",
            operations=("repair", "update"),
            targets=("folder", "system_resource"),
            required=(),
            allowed=("folder", "system_resource"),
            disallowed=("conceptual cleanup advice",),
            risks=("dry_run_plan", "local_mutation"),
            positive=("clean up downloads", "archive stale files"),
            negative=("clean writing style",),
            near=("clean up this paragraph",),
            missing="clarify destructive target if absent",
            tools=("maintenance_action",),
        ),
        _spec(
            "trust_approvals",
            "trust",
            operations=("verify", "status"),
            targets=("prior_result", "unknown"),
            required=("approval_object",),
            allowed=("prior_result",),
            disallowed=("generic permission concept",),
            risks=("trust_sensitive_action",),
            positive=("approve", "deny", "allow", "confirmation"),
            negative=("approval policy discussion",),
            near=("what is approval voting",),
            missing="route trust_approvals and clarify for approval_object",
            tools=(),
        ),
        _spec(
            "terminal",
            "terminal",
            operations=("open", "launch"),
            targets=("folder", "workspace"),
            required=("folder_context",),
            allowed=("folder", "workspace", "current_file"),
            disallowed=("conceptual terminal discussion",),
            risks=("internal_surface_open",),
            positive=("open terminal", "command shell"),
            negative=("terminal illness", "terminal value"),
            near=("terminal velocity explanation",),
            missing="clarify for working directory when deictic",
            tools=("shell_command",),
        ),
        _spec(
            "desktop_search",
            "workflow",
            operations=("search", "open"),
            targets=("file", "folder", "workspace", "unknown"),
            required=(),
            allowed=("file", "folder", "workspace"),
            disallowed=("web search", "conceptual search"),
            risks=("read_only", "internal_surface_open"),
            positive=("find files", "search desktop", "recent files"),
            negative=("research online", "search the web"),
            near=("search algorithms explanation",),
            missing="clarify when search target is too vague",
            tools=("desktop_search", "recent_files"),
        ),
        _spec(
            "power",
            "system",
            operations=("status", "inspect"),
            targets=("system_resource",),
            required=(),
            allowed=("system_resource",),
            disallowed=("political power concept",),
            risks=("read_only",),
            positive=("battery", "power", "charging", "time to empty"),
            negative=("power dynamics essay",),
            near=("explain power in physics",),
            missing="not usually required",
            tools=("power_status", "power_projection", "power_diagnosis"),
        ),
        _spec(
            "machine",
            "system",
            operations=("status", "inspect"),
            targets=("system_resource",),
            required=(),
            allowed=("system_resource",),
            disallowed=("machine learning concept",),
            risks=("read_only",),
            positive=("machine name", "os version", "this computer", "timezone"),
            negative=("machine learning model comparison",),
            near=("what is machine learning",),
            missing="not usually required",
            tools=("machine_status", "resource_status"),
        ),
        _spec(
            "resources",
            "system",
            operations=("status", "inspect"),
            targets=("system_resource",),
            required=(),
            allowed=("system_resource",),
            disallowed=("conceptual resources",),
            risks=("read_only",),
            positive=("cpu", "memory", "ram", "resource usage"),
            negative=("human resources", "study resources"),
            near=("what resources should I read",),
            missing="not usually required",
            tools=("resource_status",),
        ),
    ]
    return {spec.route_family: spec for spec in specs}


def _spec(
    route_family: str,
    subsystem: str,
    *,
    operations: tuple[str, ...],
    targets: tuple[str, ...],
    required: tuple[str, ...],
    allowed: tuple[str, ...],
    disallowed: tuple[str, ...],
    risks: tuple[str, ...],
    positive: tuple[str, ...],
    negative: tuple[str, ...],
    near: tuple[str, ...],
    missing: str,
    tools: tuple[str, ...],
) -> RouteFamilySpec:
    return RouteFamilySpec(
        route_family=route_family,
        subsystem=subsystem,
        owned_operations=operations,
        owned_target_types=targets,
        required_context_types=required,
        allowed_context_types=allowed,
        disallowed_context_types=disallowed,
        risk_classes=risks,
        positive_intent_signals=positive,
        negative_intent_signals=negative,
        near_miss_examples=near,
        missing_context_behavior=missing,
        clarification_template=missing,
        tool_candidates=tools,
        overcapture_guards=negative,
    )
